import './globals.css'
import { Orbitron,Rajdhani,Aldrich } from "next/font/google";
<<<<<<< HEAD
import { SpeedInsights } from "@vercel/speed-insights/next";
=======
import { Analytics } from '@vercel/analytics/react';

>>>>>>> 21f1b4226d3bb4726d5ab71d9df9ed2346d4d6be
 
const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--orbitron-font",
  display: "swap",
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--rajdhani-font",
  display: "swap",
});

const aldrich = Aldrich({
  subsets: ["latin"],
  weight: "400",
  variable: "--aldrich-font",
  display: "swap",
});

export const metadata = {
  title: 'DEEPAK KUMAR',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${rajdhani.variable}  ${aldrich.variable}`}
      >
        {children}
        <Analytics />

      </body>
    </html>
  );
}
